build:
	mvn compile -f "/home/boj/code/fac/M1/GIF-4104/TP5/tp5/pom.xml"

run: build
	java -classpath "/home/boj/code/fac/M1/GIF-4104/TP5/tp5/target/classes:/opt/apache-spark/jars/*" -Xss5m com.tp5.Main